[package]
name = "rusted_nes"
version = "0.1.0"
authors = ["s-ktmy <sqrt.trill425@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "*"